export default {
  CHANGE_EVENT: 'CHANGE',
  RECIEVED_TODOS: 'RECIEVED_TODOS',
  RECIEVED_ONE_TODO: 'RECIEVED_ONE_TODO',
  DELETE_TODO_PROCESSED: 'DELETE_TODO_PROCESSED',
  RECIEVED_COMPLETED_TODO: 'RECIEVED_COMPLETED_TODO',

  RECIEVED_ACTIVITIES: 'RECIEVED_ACTIVITIES',

  RECIEVED_RESOURCES: 'RECIEVED_RESOURCES',
  RECIEVED_ONE_RESOURCE: 'RECIEVED_ONE_RESOURCE'
}
